src/index.tsx
Right now offsetted cells slide once more after you release. This change will snap them into place instead, which looks a bit better 🙂
=> Prevent slide animation after release

example/package-lock.json, package.json, src/index.tsx
Turns out it's [a bug from React Native](https://github.com/facebook/react-native/issues/4753) with `measure()`. We now use `LayoutChangeEvent`'s own rectangle instead of `measure()`.
Fixes #4
=> fix: Android now works

src/index.tsx
I found this problem where sometimes instead of moving the item, the list scrolls.
I managed to solve it by disabling the scroll on the FlatList while we have an activeKey.
=> Disable FlatList scroll while dragging

README.md, example/App.tsx, src/index.tsx
Made this backward compatible so that existing clients aren't broken, but have also marked the old functions deprecated.
=> feat: rename onStartDrag to onDragStart and onEndDrag to onDragEnd #17

example/App.tsx, example/package-lock.json, src/index.tsx
onLayout is not sent during moves, only during resizes, and so we need to update the y position to the latest whenever you begin dragging.
=> fix: update y position upon panResponderGrant to capture list position on screen

src/index.tsx
- ~~Expose the DataList props, for typing~~
- Do not require a promise for onHoverChanged and onReordered.
~~No idea why `ForwardRefFn` makes the component loose all typing,~~
~~However, if you expose the DataList props, we can pass it back to the component along with our data type to fix it, see the changes in ReadMe.~~
=> events can receive a void callback

example/App.tsx, example/package-lock.json, src/index.tsx
Not sure this is absolutely necessary, but it prevents people from rapidly reordering things so quickly that stale indices are used.
=> fix: block rapid reordering from using stale indices

src/index.tsx
On android, when dragging, the item is placed around 50px below the touch point.
The reason is that: we use the measureInWindow which does not really return screencoordinate.
=> Use measure instead of measureInWindow to get screen coordinate

src/DragListContext.tsx, src/index.tsx
This adds a support for "horizontal" lists (requested in https://github.com/fivecar/react-native-draglist/issues/29) like this:
```
<DragList
horizontal={true}
data={data}
keyExtractor={keyExtractor}
renderItem={renderItem}
onReordered={onReordered}
/>
```
I know that the implementation is not elegant in the slightest, but I'm not a TypeScript or React developer and I just wanted to make it work _somehow_, which it does.
If someone can make the implementation more generic, it would be great.
The change with `function DragListImpl<T>(props: Props<T>, reference: React.ForwardedRef<FlatList<T>>)` is indended to get rid of the error message:
`Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?`
=> Add simple support for horizontal lists

src/index.tsx
This reverts #31, which began to cause warnings and issues in React Native (because function components can't take a ref).
We then update how we handle the refs in Typescript so that there are no Typescript errors when you use the component. Verified working via example app.
=> Revert "fix: remove typescript bypass on forwardRef (#31)"

src/index.tsx
This implements the suggested change in #38 . It fixes the `measure` parameters. An already existing example of the correct parameters can be seen in the const onDragLayout.
=> Fix position of item being dragged

example/ios/Podfile, example/ios/Podfile.lock, src/index.tsx
React Native docs say Android needs this experimental flag to be on if you use LayoutAnimation, but we don't. It had been causing some crashes, so here's the fix.
=> fix: #40 - remove LayoutAnimation related code

src/index.tsx
We calculated downward scrolling incorrectly, so would auto-scroll more in a single hop as you dragged items further down in a scrolling list. This normalizes the scroll speed to be the same in both directions.
=> fix: #25 - scroll equally fast downward

src/index.tsx
We now use the center of the active item to determine when items above and below it should shift to give it space.
=> fix: Use center of active item for placement

src/index.tsx
It turns out if you set elevation to non-Animated values, those views will permanently not have changeable elevations. Seems like a bug in the React Native library, introduced in 0.76.3 (or thereabouts). This now conforms all settings of elevation and zindex to Animated values.
=> fix: maintain elevation on all active items

example/package-lock.json, package-lock.json, package.json, src/index.tsx
Removed the forwardRef declaration from the index.tsx and instead used a different approach to propagate types past the forwardRef (which otherwise removes the type inference/binding based on the data prop).
=> fix: #68 - forwardRef declaration

example/package-lock.json, src/index.tsx
Not positive this fixes #70, but there's at least one issue, which is that `measure()` calls its callback asynchronously, so some values relied on in several of the panResponder functions are incorrect if you perform them prior to the measurement being complete.
In particular, for #70, it's likely `grantActiveCenterOffsetRef.current` that ends up incorrect if you blow past the `measure()` too quickly.
This PR:
- Adds a `flatWrapRefPosUpdatedRef` to track whether the `measure()` callback has been called.
- Moves the `grantActiveCenterOffsetRef` calculation to after the `measure()` callback has been called.
- Skips processing onPanResponderMove if the `measure()` callback hasn't been called yet.
=> fix: #70 Timing fix for async measure call

src/index.tsx
This keeps our ref up to date with property changes, which we really should have done all along.
=> feat: #78 Keep `onHoverChanged` up to date

src/DragListContext.tsx, src/index.tsx
There was a timing issue between when `pan.setValue(0)` was called relative to when the newly-reordered list is rendered. I investigated a bunch of ways to fix this, including mirroring the list, but in the end the best way is to hide the dragged object briefly when the list is re-rendered so it doesn't jump visually on the screen.
=> fix: #76 Remove flicker on reorder

src/index.tsx
We still don't have a long-term fix, but this at least fixes #81, which caused Android items to disappear after dropping them.
This is not the long-term fix, since this causes the dragged item to flicker once back into its original position. But the list isn't as jumpy as when #80 when in. This unblocks/unbreaks Android until we have a longer-term fix. (iOS continues to work fine, seemingly).
=> fix: #81 Patch Android for disappearing item

src/DragListContext.tsx, src/index.tsx
- Eliminate `pan.setValue`, which stopped working reliably in recent RN
versions if you're using native driver. Instead, always use Animation
to set it.
- Move ref updates to `useMemo` in order to make them synchronous with
render.
- get rid of panOpacity
- abstract keyExtractor to change keys during reordering
- simplify cell rendering back to memoized style
- move activeKey and activeIndex to ActiveData.
=> fix: #76 Sync ref state synchronously with render

src/index.tsx
When we move to a ref, we should re-render deliberately when data changes. Otherwise React may not re-render after the `useEffect`.
=> fix: Need to re-render when data changes

src/index.tsx
`extraData` is used deliberately to trigger re-renders. But since we were passing the same object to it in multiple instances, it complained. This makes it not complain.
=> fix: Fool WDYR into not complaining about rerender
